<!--
  UpdatePrompt — a new build waits to be let in (pre-2.0 R3).

  The app shipped `registerType: "autoUpdate"` with `self.skipWaiting()` at the
  service worker's module scope, which together mean: the moment a new build
  finishes downloading, it activates and the page reloads. Mid-session.
  Mid-form. The employee typing a leave reason loses it to a reload nobody
  asked for, and cannot tell what happened.

  The checklist asks that update behaviour be CONTROLLED and that "new
  deployments do not leave users stuck on old broken assets". Those pull
  against each other, and the resolution is this: the new build is downloaded
  and ready immediately, and it takes the page when the employee says so. A
  reload they chose costs them nothing; one they did not costs them whatever
  they had typed.

  NOT dismissible, and not on a timer. Dismissing would leave them on the old
  build with no way back to the offer, which is the "stuck on old assets" half
  of the same rule. It sits at the bottom, above the tab bar, until pressed.
-->
<template>
	<Transition name="g-update">
		<div v-if="needRefresh" class="g-update" role="status">
			<span class="g-update__text">{{ __("A new version is ready.") }}</span>
			<button type="button" class="g-update__action g-focusable" @click="reload">
				{{ __("Reload") }}
			</button>
		</div>
	</Transition>
</template>

<script setup>
import { inject, ref } from "vue"

const __ = inject("$translate")

const needRefresh = ref(false)
let updateServiceWorker = null

// `virtual:pwa-register` is generated by vite-plugin-pwa at build time and does
// not exist under the node test runner or in `vite dev` without the plugin —
// so the import is dynamic and its failure is not an error. A dev session
// simply never sees the prompt, which is correct: there is no service worker
// there to update.
import("virtual:pwa-register")
	.then(({ registerSW }) => {
		updateServiceWorker = registerSW({
			onNeedRefresh() {
				console.info("[update] a new build is waiting")
				needRefresh.value = true
			},
			onOfflineReady() {
				console.info("[update] the app is cached and works offline")
			},
		})
	})
	.catch(() => {
		console.info("[update] no service worker in this environment")
	})

function reload() {
	// `true` reloads the page once the new worker has taken control — the
	// worker is told to skipWaiting from HERE, after the employee agreed,
	// rather than unconditionally at install time.
	updateServiceWorker?.(true)
}
</script>
