<!--
  UpdatePrompt — a new build waits to be let in (pre-2.0 R3).

  The app shipped `registerType: "autoUpdate"` with `self.skipWaiting()` at the
  service worker's module scope, which together mean: the moment a new build
  finishes downloading, it activates and the page reloads. Mid-session.
  Mid-form. The employee typing a leave reason loses it to a reload nobody
  asked for, and cannot tell what happened.

  The checklist asks that update behaviour be CONTROLLED and that "new
  deployments do not leave users stuck on old broken assets". Those pull
  against each other, and the resolution is this: the new build is downloaded
  and ready immediately, and it takes the page when the employee says so. A
  reload they chose costs them nothing; one they did not costs them whatever
  they had typed.

  DISMISSIBLE, which it was not at first. The reasoning then was that closing
  it would strand the employee on the old build with no way back to the offer —
  the "stuck on old assets" half of the same rule. On a real phone that came
  out as a bar nobody could clear, sitting over the bottom of every screen
  (owner, 22 Sep 2026: "it kinda stuck ... cant swipe or clear that").
  The resolution is that dismissing is not refusing: the new build is still
  downloaded and still takes over on the NEXT full load, which on a PWA people
  leave open is the next time they cold-start it. So the offer can be put away
  without being lost.

  AND THE DISMISSAL HAD TO BE REMEMBERED. Reported 23 September 2026 — "the new
  version is still popping every time". Dismissing flipped a ref and nothing
  else: the waiting worker stayed waiting, so the next load registered it
  again, onNeedRefresh fired again, and the bar came back on every single
  reload until the employee gave in and tapped Reload. A dismissal the app
  forgets is not a dismissal; it is a delay.

  Remembered PER BUILD rather than for a period (see utils/updatePromptMemory):
  an update is a specific build, it stops mattering the moment a newer one
  lands, and a timed silence would hide a genuinely urgent fix.
-->
<template>
	<Transition name="g-update">
		<div v-if="needRefresh" class="g-update" role="status">
			<span class="g-update__text">{{ __("A new version is ready.") }}</span>
			<button type="button" class="g-update__action g-focusable" @click="reload">
				{{ __("Reload") }}
			</button>
			<button
				type="button"
				class="g-update__dismiss g-focusable"
				:aria-label="__('Not now')"
				@click="dismiss"
			>
				<X :size="16" />
			</button>
		</div>
	</Transition>
</template>

<script setup>
import { inject, ref } from "vue"
import { X } from "lucide-vue-next"

import { UPDATE_DISMISS_KEY, shouldOfferUpdate, waitingBuildId } from "@/utils/updatePromptMemory"

const __ = inject("$translate")

const needRefresh = ref(false)
let updateServiceWorker = null
//: The build currently waiting, so a dismissal can name what it dismissed.
//: Captured at registration because `onNeedRefresh` takes no arguments.
let waitingId = null

//: Storage is a CONVENIENCE, never a dependency — private mode and cleared
//: site data both throw on access, and the update offer has to work anyway.
//: Failing to read means "not dismissed", which shows the bar: the safe
//: direction, since the other one strands somebody on a broken build.
function remembered() {
	try {
		return localStorage.getItem(UPDATE_DISMISS_KEY)
	} catch {
		return null
	}
}

function remember(id) {
	if (!id) return
	try {
		localStorage.setItem(UPDATE_DISMISS_KEY, id)
	} catch {
		// Nothing to do. The bar will be offered again next load, which is the
		// old behaviour and still correct — just noisier.
		console.info("[update] could not remember the dismissal; storage is unavailable")
	}
}

// `virtual:pwa-register` is generated by vite-plugin-pwa at build time and does
// not exist under the node test runner or in `vite dev` without the plugin —
// so the import is dynamic and its failure is not an error. A dev session
// simply never sees the prompt, which is correct: there is no service worker
// there to update.
import("virtual:pwa-register")
	.then(({ registerSW }) => {
		updateServiceWorker = registerSW({
			// The registration is where the waiting worker's identity lives —
			// `onNeedRefresh` takes no arguments, so the id has to be captured
			// here and read when the offer fires.
			onRegisteredSW(_url, registration) {
				waitingId = waitingBuildId(registration)
			},
			onNeedRefresh() {
				if (!shouldOfferUpdate(waitingId, remembered())) {
					console.info("[update] a build is waiting, and this one was already put away")
					return
				}
				console.info("[update] a new build is waiting")
				needRefresh.value = true
			},
			onOfflineReady() {
				console.info("[update] the app is cached and works offline")
			},
		})
	})
	.catch(() => {
		console.info("[update] no service worker in this environment")
	})

function dismiss() {
	// Hides the offer, does not decline the build. The worker stays waiting and
	// activates on the next cold start; nothing is lost by putting it away.
	//
	// REMEMBERED, which it was not: without this the next load offered the same
	// build again, and the one after that, until the employee gave in.
	console.info("[update] the employee put the offer away; it will apply on the next load")
	remember(waitingId)
	needRefresh.value = false
}

function reload() {
	// `true` reloads the page once the new worker has taken control — the
	// worker is told to skipWaiting from HERE, after the employee agreed,
	// rather than unconditionally at install time.
	//
	// The remembered dismissal is cleared first. It belongs to a build that is
	// about to become the CURRENT one, and a stale key sitting in storage is a
	// coincidence waiting to suppress a future offer.
	try {
		localStorage.removeItem(UPDATE_DISMISS_KEY)
	} catch {
		// Storage being unavailable cannot stop a reload the employee asked for.
	}
	updateServiceWorker?.(true)
}
</script>
